### ISSUE TITLE
Ensure two \r line is added back into .gitignore file

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/css_layout_with_bootstrap#25]
This line was erroneously removed from `.gitignore` during 016's update. 

```diff
 # Icon must end with two \r
-Icon^M^M
+Icon
```

(reverse the diff to fix)

It needs to be `Icon^M^M` as the above comment dictates. Please see discussion here. https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass/pull/23#discussion_r97571293

**Comment by gaand** [comment]
Closed but not recorded in a template update.  I don't want to spend the time finding the close.  I have verified the double carriage return with @Jcornmanhomonoff
