### ISSUE TITLE
Reflow this paragraph in README

### ISSUE THREAD

**Issue by BenGitsCode** [ga-wdi-boston/css_layout_with_bootstrap#26]
```diff
## Bootstrap Documentation

For components and jQuery plugins always reference the Bootstrap docs.

 [Bootstrap Documentation](http://getbootstrap.com/)

+Do not use premade bootstrap templates.
+They often have alternate versions of jQuery or Bootstrap which are different
+than the versions we will be using to practice.
```

See this discussion https://github.com/ga-wdi-boston/html-css-layout-bootstrap-sass/pull/23#discussion_r97571293

**Comment by gaand** [comment]
We may need to talk about the various meanings of "template".

**Comment by jrhorn424** [comment]
I agree. I'm not sure there's adequate explanation of why not to use a template, or what a template is in this context. I'll reopen #20.
